### ISSUE TITLE
HSize column value is truncated

### ISSUE THREAD

**Issue by dtaraf** [mazenharake/entop#17]
Hello,

I have been using this tool for some days now and am finding it very useful. One issue however is that the HSize ( which happens to be the column that I am using most) is showing truncated values 

E.g ordering on the column HSize:

Pid Registered Name      Reductions   MQueue HSize  SSize HTot                                        

```
    <0.563.0>  -                                5818505      0      156725   9      156725
    <0.476.0>  -                                 876170       0      832040   9      832040
```

If I do a process_info for the heap size on this process then I see the value {heap_size,15672560}. 

Could you please advise  how I can fix ?

Thanks for any assistance,
Devangana Tarafdar

**Comment by djnym** [comment]
This should be bigger now (I think it's set to 12 now.  If it's still an issue please reopen, but closing for now.
